Neos:
  Neos:
    fusion:
      autoInclude:
        'ByTorsten.FormBuilder': TRUE
    nodeTypes:
      groups:
        formfields:
          position: 'after general'
          label: 'Form fields'
          collapsed: false
ByTorsten:
  FormBuilder:
    finishers:
      mailer:
        class: 'ByTorsten\FormBuilder\Finisher\MailerFinisher'
        options:
          from: "noreply@domain.com"
      redirect:
        position: 'end'
        class: 'ByTorsten\FormBuilder\Finisher\RedirectFinisher'
    recaptcha:
      siteKey: ""
      secretKey: ""